/**
 * Single source of truth for the Skulltula interactive map's background
 * regions — one hand-laid-out schematic per top-level overworld hub
 * (`SkulltulaArea`, matching `content.config.ts`'s `skulltulaAreaSchema`).
 *
 * Each area is its own 0-100 x 0-100 canvas. `AREA_REGIONS[area]` lists the
 * fine-grained `zone` values that live inside that hub as non-overlapping
 * boxes (`x0,y0,x1,y1`) — drawn as the map's schematic terrain blocks by
 * `SkulltulaMap.tsx`. Every skulltula's `x`/`y` (content.config.ts) was
 * generated by placing that zone's items on a small grid inset within its
 * own box, so a pin can never render outside its zone's drawn region. This
 * is a stylized illustration, not a real screenshot of the game — OoT 3D's
 * actual map art isn't ours to redistribute, and the site's own emerald/gold
 * palette reads better here than a literal minimap anyway.
 */

export const AREA_ORDER = [
  'kokiri',
  'hyrule-field',
  'kakariko',
  'death-mountain',
  'zora',
  'lake-hylia',
  'gerudo',
] as const;

export type SkulltulaArea = (typeof AREA_ORDER)[number];

export interface ZoneRegion {
  zone: string;
  box: readonly [x0: number, y0: number, x1: number, y1: number];
  /** Dungeon/interior zones get a slightly different fill treatment
   * (see SkulltulaMap.tsx) so the schematic reads as "inside a structure"
   * vs. open overworld, without needing a whole second art style. */
  interior: boolean;
}

export const AREA_REGIONS: Record<SkulltulaArea, ZoneRegion[]> = {
  kokiri: [
    { zone: 'Kokiri Forest', box: [52, 58, 88, 88], interior: false },
    { zone: 'Inside the Deku Tree', box: [62, 18, 90, 46], interior: true },
    { zone: 'Lost Woods', box: [24, 50, 50, 82], interior: false },
    { zone: 'Sacred Forest Meadow', box: [8, 60, 22, 84], interior: false },
    { zone: 'Forest Temple', box: [6, 14, 34, 48], interior: true },
  ],
  'hyrule-field': [
    { zone: 'Hyrule Castle Market', box: [38, 6, 62, 24], interior: false },
    { zone: 'Hyrule Castle', box: [38, 28, 62, 46], interior: true },
    { zone: "Ganon's Castle", box: [42, 48, 58, 53], interior: true },
    { zone: 'Hyrule Field', box: [10, 55, 46, 92], interior: false },
    { zone: 'Lon Lon Ranch', box: [54, 55, 90, 88], interior: false },
  ],
  kakariko: [
    { zone: 'Graveyard', box: [30, 15, 65, 40], interior: false },
    { zone: 'Shadow Temple', box: [5, 8, 28, 38], interior: true },
    { zone: 'Kakariko Village', box: [30, 45, 75, 85], interior: false },
    { zone: 'Bottom of the Well', box: [78, 45, 98, 72], interior: true },
  ],
  'death-mountain': [
    { zone: 'Death Mountain Crater', box: [55, 6, 85, 24], interior: false },
    { zone: "Dodongo's Cavern", box: [55, 28, 80, 52], interior: true },
    { zone: 'Fire Temple', box: [15, 8, 48, 40], interior: true },
    { zone: 'Goron City', box: [20, 45, 50, 80], interior: true },
    { zone: 'Death Mountain Trail', box: [55, 55, 92, 90], interior: false },
  ],
  zora: [
    { zone: "Zora's Fountain", box: [55, 8, 85, 32], interior: false },
    { zone: 'Ice Cavern', box: [30, 8, 52, 32], interior: true },
    { zone: "Zora's Domain", box: [55, 35, 85, 58], interior: false },
    { zone: 'Water Temple', box: [5, 35, 28, 80], interior: true },
    { zone: "Inside Jabu-Jabu's Belly", box: [30, 55, 52, 88], interior: true },
    { zone: "Zora's River", box: [55, 60, 92, 92], interior: false },
  ],
  'lake-hylia': [{ zone: 'Lake Hylia', box: [10, 15, 90, 85], interior: false }],
  gerudo: [
    { zone: "Gerudo's Fortress", box: [68, 15, 95, 48], interior: false },
    { zone: 'Desert Colossus', box: [38, 10, 62, 38], interior: false },
    { zone: 'Haunted Wasteland', box: [38, 45, 62, 82], interior: false },
    { zone: 'Spirit Temple', box: [5, 15, 32, 75], interior: true },
    { zone: 'Gerudo Valley', box: [68, 55, 95, 88], interior: false },
  ],
};
